services:
  be-binareversi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
      - air-config:/root/.air
    working_dir: /app
    command: air
    environment:
      - AIR_CONFIG=.air.toml
    depends_on:
      - wait

  wait:
    image: busybox
    command: sh -c "sleep 1"

  fe-binareversi:
    build: ../fe-binareversi
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ../fe-binareversi/app:/app
      - node_modules:/app/node_modules

volumes:
  air-config:
  node_modules:
