services:
  be-binareversi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - air-config:/root/.air
    working_dir: /app
    command: air
    environment:
      - AIR_CONFIG=.air.toml
    depends_on:
      - wait
  wait:
    image: busybox
    command: sh -c "sleep 1"

  fe-binareversi:
    build: ../fe-binareversi
    ports:
      - "5173:5173"

volumes:
  air-config:
